[build-system]
requires = [
    "setuptools>=42",
    "scikit-build>=0.13",
    "cmake>=3.1",
    "ninja",
    "pyyaml",
    "typing_extensions",
    "sympy"
]
build-backend = "setuptools.build_meta"
