name: runs on ascend

on:
  workflow_call:
    inputs:
      machine:
        description: If set to other value, the job need ssh
        type: string
        required: false
        default: "ASCEND"
      runner:
        description: Set up the build environment
        type: string
        required: false
        default: "tps-ascend-ci"

jobs:
  checkout_code:
    name: checkout code
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Code
        uses: DeepLink-org/deeplink.framework/.github/actions/checkout-code@main

  build:
    runs-on: ${{ inputs.runner }}
    needs: checkout_code
    steps:
      - name: build on ascend
        uses: DeepLink-org/deeplink.framework/.github/actions/code-build-test@main
        with:
          build_shell: "
                       source dicp/scripts/ci/ascend/ci_ascend_build_env.sh && \
                       pip uninstall torch_dipu -y && \
                       pip uninstall dicp -y && \
                       cd dipu && python setup.py install --user && \
                       cd ../dicp && python setup.py install --user
                       " 
          job_name: "build"
          cover_job: "0"
          cleaner: "clean_all_if_error"

  test:
    runs-on: ${{ inputs.runner }}
    needs: build
    steps:
      - name: rt test on ascend
        uses: DeepLink-org/deeplink.framework/.github/actions/code-build-test@main
        with:
          build_shell: "
                        cd .. && source dicp/scripts/ci/ascend/ci_ascend_test_env.sh /mnt/models/llama_models && \
                        export TEST_DIR=$(pwd)/dicp/test && echo ${TEST_DIR} && \
                        bash ${TEST_DIR}/ascend_scripts/ops/run_test_ops.sh false && \
                        bash ${TEST_DIR}/ascend_scripts/models/run_test_models.sh false
                        "
          job_name: "test"
          cover_job: "1"
