name: diopi ce
on:
  workflow_dispatch:
  push:
    branches:
      - "wgs/**"
  
#  schedule:
#    - cron: '30 11 * * 6'
env:
  target_file: "/home/autolink/rsync/train_flag"
  source_file: "/artifacts/train_flag"

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  Archive_Results:
    name: archive train results
    runs-on: github-tps-ce
    steps:
      - name: start to check
        run: |
          diff_output=$(diff -q --ignore-all-space  "$target_file" "$source_file" ) && export result=0 || export result=1
          if [ $result -eq 0 ]; then
            echo "The file content is the same,results have been collected"
            exit 1
          fi
      - name: start to archive
        uses: actions/upload-artifact@v3
        with:
          name: train-results
          path: /artifacts/**
      - name: start to clean
        run: |
          cp -r ${source_file} ${target_file}


    
