name: diopi ce
on:
  workflow_dispatch:
#  schedule:
#    - cron: '30 11 * * 6'

env:
  artifacts_path: /data/platform_ci/nginxweb/parrots/train/artifacts

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  Archive_Results:
    name: archive train results
    runs-on: github-poc-ci
    steps:
      - name: start to check
        run: |
          cd ${artifacts_path} 
          if [ ! -f train_flag ]; then
            echo "have been collected"
            exit 1
          fi
      - name: start to archive
        uses: actions/upload-artifact@v3
        with:
          name: train-results
          path: ${artifacts_path}/*.*
      - name: start to clean
        run: |
          cd ${artifacts_path} && rm -rf train_flag


    
