name: diopi ce
on:
  workflow_dispatch:
  push:
    branches:
      - "wgs/**"
  
#  schedule:
#    - cron: '30 11 * * 6'


concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  Archive_Results:
    name: archive train results
    runs-on: github-tps-ce
    steps:
      - name: start to check
        run: |
          cd /artifacts
          if [ ! -f train_flag ]; then
            echo "Results have been collected"
            exit 1
          fi
      - name: start to archive
        uses: actions/upload-artifact@v3
        with:
          name: train-results
          path: /artifacts/*.*
      - name: start to clean
        run: |
          cd /artifacts && rm -rf train_flag


    
