name: dicp ci
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/dicp.yml"
      - ".github/workflows/_runs-on-ascend.yml"
      - ".github/workflows/_runs-on-topsrider.yml"
      - "dicp/**"

env:
  ENV_PATH: '/mnt/cache/share/platform/env'
  DEEPLINK_PATH: '/mnt/cache/share/deeplinkci/github/${{ github.repository }}'

concurrency:
  group: dicp-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  runs-on-topsrider:
    name: runs on topsrider
    uses: ./.github/workflows/_runs-on-topsrider.yml

  runs-on-ascend:
    name: runs on ascend
    uses: ./.github/workflows/_runs-on-ascend.yml
