name: pytorch ci

on:
  pull_request:
  push:
    branches:
      - wgs/*
  workflow_dispatch:

env:
  PVC_PATH: '/nvme/share/share/github/cibuild/${{ github.repository }}'
  SOURCE_PATH: '/nvme/share/share/github/sourcecode'
  HOME: "/var/lib/jenkins"
  CI_IMAGE: "registry.sensetime.com/parrots/parrots:linux-bionic-cuda11.7-cudnn8-py3-gcc7"
  BUILD_ENVIRONMENT: "linux-bionic-cuda11.7-py3.10-gcc7"
  PYTORCH_COMMIT: "461f088"
  https_proxy: "http://10.1.8.5:32680/"

jobs:
  Checkout:
    name: pull and rsync
    runs-on: tps-pytorch-ci
    timeout-minutes: 240
    steps:
      - name: rsync repo
        run: |
          cd ${SOURCE_PATH}/pytorch/pytorch && git pull
          cd ${PVC_PATH} && rm -rf ${GITHUB_RUN_NUMBER} && mkdir -p ${GITHUB_RUN_NUMBER}/artifacts
          rsync -a ${SOURCE_PATH}/pytorch/pytorch ${PVC_PATH}/${GITHUB_RUN_NUMBER}/
          cd ${PVC_PATH}/${GITHUB_RUN_NUMBER}
          mv pytorch source && cd source && git checkout ${PYTORCH_COMMIT} && git submodule sync && git submodule update --init --recursive
#          cd ${SOURCE_PATH}/${{ github.event.repository.full_name }} && git pull
#          cd ${PVC_PATH} && rm -rf ${GITHUB_RUN_NUMBER} && mkdir -p ${GITHUB_RUN_NUMBER}/artifacts
#          rsync -a ${SOURCE_PATH}/${{ github.event.repository.full_name }} ${PVC_PATH}/${GITHUB_RUN_NUMBER}/
#          cd ${PVC_PATH}/${GITHUB_RUN_NUMBER}
#          mv ${{ github.event.repository.name }} source && cd source && git checkout ${{ github.sha }} && git submodule sync && git submodule update --init --recursive

  linux-cuda117-py310-gcc7-build:
    name: linux-cuda117-py310-gcc7-build
    runs-on: tps-pytorch-ci
    needs: [Checkout]
    timeout-minutes: 240
    env:
      TORCH_CUDA_ARCH_LIST: "Volta;7.0;7.5;8.0;8.6"
      GPU_NUM: 1
      DEBUG: 0
    steps:
      - name: build
        run: |
          set -e
          set -o pipefail
          cd ${PVC_PATH}/${GITHUB_RUN_NUMBER}/source && echo '${{ toJSON(env) }}' |grep -v '{\|}'> ${GITHUB_JOB} && sed -i 's/\"//g' ${GITHUB_JOB} && sed -i 's/,//g' ${GITHUB_JOB} && sed -i 's/:[ ]/=\"/g' ${GITHUB_JOB} && sed -i 's/$/&\"/' ${GITHUB_JOB} && sed -i 's/^/&export/' ${GITHUB_JOB}
          docker ps -aq -f status=exited | xargs -r docker rm || echo "no exiting container" && docker rm -f ${GITHUB_RUN_ID}_${GITHUB_JOB}
          container_name=$(docker run --tty --detach \
          -v ${PVC_PATH}/${GITHUB_RUN_NUMBER}/:/home/ \
          -v ${SOURCE_PATH}/tools:${HOME}/tools \
          ${CI_IMAGE} )
          docker exec -t "${container_name}" bash -c "source /home/source/${GITHUB_JOB} && ${HOME}/tools/run.sh build " && docker rm -f ${container_name} || ( docker rm -f ${container_name} && exit 1 )

  linux-cuda117-py310-gcc7-test:
    name: linux-cuda117-py310-gcc7-test
    uses: ./.github/workflows/_linux-test.yml
    needs: [linux-cuda117-py310-gcc7-build]
    with:
      test-matrix: |
        { include: [
        { config: "default", shard: 1, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 2, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 3, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 4, num_shards: 5, gpu_num: 1 },
        { config: "default", shard: 5, num_shards: 5, gpu_num: 1 },
        { config: "distributed", shard: 1, num_shards: 3, gpu_num: 2 },
        { config: "distributed", shard: 2, num_shards: 3, gpu_num: 2 },
        { config: "distributed", shard: 3, num_shards: 3, gpu_num: 2 },
        ]}
